[tool.poetry]
name = "algo-py"
version = "0.1.0"
description = ""
authors = ["Weiliang Li <to.be.impressive@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
ipython = "^7.19.0"
mypy = "^0.790"
flake8 = "^3.8.4"
black = "^20.8b1"
pytest = "^6.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
