name: Build

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"

      - run: poetry install

      - run: poetry run pytest -s --cov=algo tests --cov-report xml

      - uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
